use soroban_sdk::contracterror;

#[contracterror]
#[derive(Copy, Clone, Debug, Eq, PartialEq, PartialOrd, Ord)]
#[repr(u32)]
pub enum ErrorCode {
    AlreadyInitialized = 100,
    NotAuthorized = 101,
    MarketNotFound = 102,
    MarketClosed = 103,
    MarketStillActive = 104,
    InvalidOutcome = 105,
    InvalidBetAmount = 106,
    InsufficientBalance = 107,
    OracleFailure = 108,
    StalePrice = 109,
    ConfidenceTooLow = 110,
    InvalidTimestamp = 111,
    CircuitBreakerOpen = 112,
    DisputeWindowClosed = 113,
    VotingNotStarted = 114,
    VotingEnded = 115,
    AlreadyVoted = 116,
    FeeTooHigh = 117,
    MarketNotActive = 118,
    DeadlinePassed = 119,
    CannotChangeOutcome = 120,
    MarketNotDisputed = 121,
    MarketNotPendingResolution = 122,
    AdminNotSet = 123,
    ContractPaused = 124,
    GuardianNotSet = 125,
    TooManyOutcomes = 126,
    TooManyWinners = 127,
    PayoutModeNotSupported = 128,
    InsufficientDeposit = 129,
    TimelockActive = 130,
    UpgradeNotInitiated = 131,
    InsufficientVotes = 132,
    AlreadyVotedOnUpgrade = 133,
    InvalidWasmHash = 134,
    UpgradeFailed = 135,
    ParentMarketNotResolved = 136,
    ParentMarketInvalidOutcome = 137,
    MarketIdOverflow = 138,
    MarketIdCollision = 139,
}
